[build]
  publish = "."

[[redirects]]
  from = "/press"
  to = "/press/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
