name: Deploy OQADAH to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site
        uses: actions/upload-pages-artifact@v4
        with:
          path: .  # or your actual build folder (e.g. `dist` or `build`)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
