name: Deploy to GitHub Pages

permissions:
  id-token: write
  contents: read
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/upload-artifact@v4
        with:
          path: ./
      - uses: actions/deploy-pages@v2
